services:
    cas:
        class: EcPhp\CasLib\Cas
        arguments:
            $serverRequest: '@psr.request'
            $properties: '@cas.configuration'
            $client: '@psr18.http_client'
            $uriFactory: '@nyholm.psr7.psr17_factory'
            $responseFactory: '@nyholm.psr7.psr17_factory'
            $requestFactory: '@nyholm.psr7.psr17_factory'
            $streamFactory: '@nyholm.psr7.psr17_factory'
            $cache: '@cache.app'
            $logger: '@logger'

    EcPhp\CasLib\CasInterface: '@cas'

    cas.configuration:
        class: EcPhp\CasBundle\Configuration\Symfony
        arguments:
            $properties: '%cas%'
            $router: '@router'

    cas.userprovider:
        class: EcPhp\CasBundle\Security\Core\User\CasUserProvider

    cas.guardauthenticator:
        class: EcPhp\CasBundle\Security\CasGuardAuthenticator
        autoconfigure: true
        autowire: true

    EcPhp\CasBundle\Controller\Homepage:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    EcPhp\CasBundle\Controller\Login:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    EcPhp\CasBundle\Controller\Logout:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    EcPhp\CasBundle\Controller\ProxyCallback:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    symfony.request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory: [ '@request_stack', getCurrentRequest]
        public: false

    Psr\Http\Message\RequestInterface:
        factory: ['@sensio_framework_extra.psr7.http_message_factory', 'createRequest']
        arguments: ['@symfony.request']

    psr.request:
        alias: 'Psr\Http\Message\RequestInterface'
        public: true

    # Fix for https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/688
    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@sensio_framework_extra.psr7.http_message_factory'
    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface: '@sensio_framework_extra.psr7.http_foundation_factory'
